### ISSUE TITLE
Part information, such as the acrylic tube?

### ISSUE THREAD

**Issue by MStylesMS** [LEDs-by-glowingkitty/GlowTower#1]
Nice projects!  

On this one, can you share where the acrylic tube can be found?

**Comment by glowingkitty** [comment]
thanks :)
I found a local company in Germany (where I live), that produces those frosted tubes (among other acrylic stuff).
https://hbholzmaus.de/

I suggest searching for companies which produce acrylic tubes in the country where you are at the moment. On Aliexpress I was only able to find the small acrylic tubes (max 3-4 cm diameter), not the 16cm diameter tube used in this project.
